name: rust-checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call:

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: step::checkout
        uses: actions/checkout@v6

      - name: step::setup
        uses: ./.github/actions/setup-rust
        with:
          components: rustfmt

      - name: step::check_formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - name: step::checkout
        uses: actions/checkout@v6

      - name: step::setup
        uses: ./.github/actions/setup-rust
        with:
          components: clippy
          install-linux-ui-deps: "true"

      - name: step::clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - name: step::checkout
        uses: actions/checkout@v6

      - name: step::setup
        uses: ./.github/actions/setup-rust
        with:
          install-linux-ui-deps: "true"

      - name: step::tests
        run: cargo test --workspace --all-targets
